# Generated by Django 5.2 on 2025-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.AddField(
            model_name='department',
            name='Dept_image',
            field=models.ImageField(default='department_images/default.png', upload_to='departments/'),
        ),
        migrations.AddField(
            model_name='department',
            name='Dept_name',
            field=models.CharField(default='Department Name', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='Faculty_member',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
