# Generated by Django 5.2 on 2025-04-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0002_remove_department_name_department_dept_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Event_image',
            field=models.ImageField(default='event_images/default.png', upload_to='event/'),
        ),
        migrations.AddField(
            model_name='event',
            name='vanue',
            field=models.CharField(default='Event Vanue', max_length=200),
        ),
    ]
