# Generated by Django 5.2 on 2025-04-23 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0003_event_event_image_event_vanue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Author Name', max_length=100)),
                ('bio', models.TextField(blank=True, default='Author biography.')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(default='Exam Name', max_length=200)),
                ('department', models.CharField(default='Department Name', max_length=100)),
                ('subject', models.CharField(default='Subject Name', max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default='09:00:00')),
                ('end_time', models.TimeField(default='12:00:00')),
                ('venue', models.CharField(default='Exam Venue', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='hostel_images/default.png', upload_to='hostels/')),
                ('title', models.CharField(default='Hostel Title', max_length=255)),
                ('description', models.TextField(default='Hostel description here.')),
                ('items_list', models.TextField(default='Item1, Item2, Item3', help_text='Enter items as a comma-separated list')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='labs/')),
                ('title', models.CharField(default='Lab Title', max_length=255)),
                ('description', models.TextField(default='Lab description here.')),
                ('items_list', models.TextField(default='Item1, Item2, Item3', help_text='Enter items as a comma-separated list')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Message Title', max_length=200)),
                ('image', models.ImageField(default='people_images/default.png', upload_to='people/')),
                ('message', models.TextField(default='Message content.')),
            ],
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Dept_image',
            new_name='dept_image',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Dept_name',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Event_image',
            new_name='event_image',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='address',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Faculty_member',
        ),
        migrations.RemoveField(
            model_name='event',
            name='vanue',
        ),
        migrations.AddField(
            model_name='admission',
            name='annual_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='department',
            field=models.CharField(default='Department Name', max_length=200),
        ),
        migrations.AddField(
            model_name='admission',
            name='duration',
            field=models.CharField(default='Duration', max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='eligibility',
            field=models.TextField(default='Eligibility criteria.'),
        ),
        migrations.AddField(
            model_name='admission',
            name='program',
            field=models.TextField(default='Program description.'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(default='Message content here.'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='Your Name', max_length=100),
        ),
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(default='Subject', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Event Venue', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news_images/default.png', upload_to='news_images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='principalmessage',
            name='image',
            field=models.ImageField(default='principal_images/default.png', upload_to='principal/'),
        ),
        migrations.AddField(
            model_name='principalmessage',
            name='title',
            field=models.CharField(default="Principal's Message Title", max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(default='About section content.'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='youremail@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, default='1234567890', max_length=15),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(default='Department description.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='Event description.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Event Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(default='Facility description.'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(default='Facility Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='library',
            name='description',
            field=models.TextField(default='Library description.'),
        ),
        migrations.AlterField(
            model_name='library',
            name='location',
            field=models.CharField(default='Library Location', max_length=200),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(default='Library Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default='News content here.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='News Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='principalmessage',
            name='message',
            field=models.TextField(default="Principal's message."),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(default='Slider description here.'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='slider_images/default.png', upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(default='Slider Title', max_length=200),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Book Title', max_length=200)),
                ('isbn', models.CharField(default='0000000000000', max_length=13, unique=True)),
                ('published_date', models.DateField()),
                ('category', models.CharField(default='Book Category', max_length=100)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='gcms_sitehub.author')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='gcms_sitehub.library')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_member',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
