# Generated by Django 5.2 on 2025-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0004_author_examschedule_hostel_lab_peoplemessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalmessage',
            name='subtitle',
            field=models.CharField(default='Empowering parents. Nurturing futures.', max_length=200),
        ),
        migrations.AlterField(
            model_name='principalmessage',
            name='image',
            field=models.ImageField(default='default_principal_image.jpg', upload_to='principal_images/'),
        ),
        migrations.AlterField(
            model_name='principalmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='principalmessage',
            name='title',
            field=models.CharField(default='Message from the Principal', max_length=200),
        ),
    ]
