# Generated by Django 5.2 on 2025-04-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0005_principalmessage_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicExcellence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(default='backgrounds/default.jpg', upload_to='backgrounds/')),
                ('heading', models.CharField(default='Academic Excellence At Our University', max_length=255)),
                ('subheading', models.CharField(default='Shape Your Future Through World-Class Education', max_length=255)),
                ('search_placeholder', models.CharField(default='Explore our academic programs...', max_length=255)),
                ('students_enrolled', models.PositiveIntegerField(default=1500)),
                ('academic_programs', models.PositiveIntegerField(default=120)),
                ('employment_rate', models.PositiveIntegerField(default=95)),
            ],
        ),
    ]
