# Generated by Django 5.2 on 2025-04-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0006_academicexcellence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('image', models.ImageField(default='testimonials/default.jpg', upload_to='testimonials/')),
            ],
        ),
    ]
