# Generated by Django 5.2 on 2025-04-23 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0007_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='GCMS Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/default.jpg', upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
