# Generated by Django 5.2 on 2025-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0008_remove_news_content_remove_news_date_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button1_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button1_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='slider',
            name='button2_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button2_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
