# Generated by Django 5.2 on 2025-04-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0010_remove_event_event_image_event_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='event_images/default.png', upload_to='event/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='Event description.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Event Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Event Venue', max_length=200),
        ),
    ]
