# Generated by Django 5.2 on 2025-04-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0011_remove_event_image_event_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='feature_1',
            field=models.CharField(default='30 workstations with i7 processors', max_length=200),
        ),
        migrations.AddField(
            model_name='facility',
            name='feature_2',
            field=models.CharField(default='Latest programming tools and IDEs', max_length=200),
        ),
        migrations.AddField(
            model_name='facility',
            name='feature_3',
            field=models.CharField(default='Interactive learning systems', max_length=200),
        ),
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.ImageField(default='facilities/default.jpg', upload_to='facilities/'),
        ),
        migrations.AddField(
            model_name='facility',
            name='title',
            field=models.CharField(default='Programming Lab', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(default='This lab is equipped with modern tools and infrastructure.'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(choices=[('programming', 'Programming Lab'), ('multimedia', 'Multimedia Lab')], default='programming', max_length=100),
        ),
    ]
