# Generated by Django 5.2 on 2025-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0012_facility_feature_1_facility_feature_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Facility Title', max_length=100)),
                ('description', models.TextField(default='This is a default description for the hostel facility.')),
                ('image', models.ImageField(default='hostel/default.jpg', upload_to='hostel/')),
                ('feature_1', models.CharField(default='Feature One', max_length=200)),
                ('feature_2', models.CharField(default='Feature Two', max_length=200)),
                ('feature_3', models.CharField(default='Feature Three', max_length=200)),
                ('feature_4', models.CharField(default='Feature Four', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HostelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi-check-circle', help_text='Bootstrap Icon class, e.g. bi-shield-check', max_length=50)),
                ('title', models.CharField(default='Default Title', max_length=100)),
                ('description', models.CharField(default='Default Description', max_length=200)),
            ],
        ),
    ]
