# Generated by Django 5.2 on 2025-04-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0013_hostelfacility_hostelfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Comfortable Living', max_length=200)),
                ('description', models.TextField(default='Our hostel facilities provide a comfortable and secure environment for students who wish to stay on campus.')),
                ('image', models.ImageField(default='hostel/default.jpg', upload_to='hostel/')),
            ],
        ),
        migrations.DeleteModel(
            name='HostelFeature',
        ),
    ]
