# Generated by Django 5.2 on 2025-04-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0015_visitrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitySlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('image', models.ImageField(upload_to='facility_sliders/')),
            ],
        ),
    ]
