# Generated by Django 5.2 on 2025-04-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0016_facilityslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Book', max_length=255)),
                ('author', models.CharField(default='Unknown Author', max_length=255)),
                ('publisher', models.CharField(default='Unknown Publisher', max_length=255)),
                ('category', models.CharField(choices=[('cs', 'Computer Science'), ('fiction', 'Fiction'), ('textbooks', 'Textbooks')], default='cs', max_length=50)),
                ('edition', models.CharField(blank=True, default='1st', max_length=50)),
                ('published_year', models.CharField(blank=True, default='2024', max_length=4)),
                ('description', models.TextField(default='No description provided.')),
                ('image', models.ImageField(default='library_books/default.jpg', upload_to='library_books/')),
            ],
            options={
                'verbose_name': 'Library Book',
                'verbose_name_plural': 'Library Books',
                'db_table': 'library_book',
            },
        ),
    ]
