# Generated by Django 5.2 on 2025-04-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0018_alter_librarybook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybook',
            name='category',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('management', 'Management'), ('engineering', 'Engineering'), ('business', 'Business'), ('ecnomics', 'Economics'), ('mathematics', 'Mathematics'), ('fiction', 'Fiction'), ('textbooks', 'Textbooks'), ('history', 'History'), ('biography', 'Biography'), ('science', 'Science'), ('math', 'Mathematics'), ('arts', 'Arts & Humanities'), ('language', 'Languages & Literature'), ('reference', 'Reference'), ('philosophy', 'Philosophy'), ('religion', 'Religion'), ('business', 'Business & Economics'), ('management', 'Management'), ('ba_economics', 'Business Administration & Economics'), ('children', "Children's Books"), ('magazines', 'Magazines & Journals')], default='cs', max_length=50),
        ),
    ]
