# Generated by Django 5.2 on 2025-04-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0019_alter_librarybook_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Admission Step', max_length=100)),
                ('icon_class', models.CharField(default='fas fa-graduation-cap', help_text='FontAwesome class (e.g., fas fa-user-graduate)', max_length=50)),
                ('description', models.TextField(default='Description of the step.')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_season', models.CharField(default='Fall 2025', max_length=50)),
                ('description', models.TextField(default='Apply for admission by downloading the application form.')),
                ('form_file', models.FileField(upload_to='admissions/forms/')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('engineering', 'Engineering'), ('business', 'Business'), ('computing', 'Computing'), ('medical', 'Medical'), ('arts', 'Arts & Humanities')], default='engineering', max_length=50)),
                ('program', models.CharField(default='Program Name', max_length=100)),
                ('fee_range', models.CharField(default='0 - 0', max_length=50)),
                ('duration', models.CharField(default='4 Years', max_length=20)),
            ],
        ),
    ]
