# Generated by Django 5.2 on 2025-04-29 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0020_admissionstep_applicationdownload_feestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('Mid-Term', 'Mid-Term'), ('Final', 'Final')], default='Mid-Term', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('subjects', models.TextField()),
                ('venue', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Scheduled', 'Scheduled')], default='Upcoming', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='General', max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='department',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='exam_name',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='venue',
        ),
        migrations.AddField(
            model_name='examschedule',
            name='time',
            field=models.CharField(default='09:00 AM', max_length=50),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='gcms_sitehub.exam'),
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Not Released', max_length=20)),
                ('release_date', models.DateField()),
                ('access_method', models.CharField(default='Online', max_length=100)),
                ('required_info', models.CharField(default='Student ID', max_length=100)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcms_sitehub.exam')),
            ],
        ),
    ]
