# Generated by Django 5.2 on 2025-04-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0021_exam_rule_remove_examschedule_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('business', 'Business'), ('computing', 'Computing'), ('management', 'Management'), ('arts', 'Arts & Humanities')], default='engineering', max_length=50),
        ),
    ]
