# Generated by Django 5.2 on 2025-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0022_alter_feestructure_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='backgrounds/')),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PhilosophyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
                ('color', models.CharField(default='primary', max_length=20)),
            ],
        ),
    ]
