# Generated by Django 5.2 on 2025-04-29 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0024_contactinformation_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='PeopleMessage',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AlterField(
            model_name='admissionstep',
            name='icon_class',
            field=models.CharField(default='fas fa-graduation-cap', help_text='FontAwesome class', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_image',
            field=models.ImageField(default='departments/default.png', upload_to='departments/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='event/default.png', upload_to='event/'),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='gcms_sitehub.exam'),
        ),
        migrations.AlterField(
            model_name='hostelintro',
            name='description',
            field=models.TextField(default='Our hostel facilities provide a comfortable and secure environment.'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='category',
            field=models.CharField(choices=[('science', 'Science'), ('reference', 'Reference'), ('engineering', 'Engineering'), ('mathematics', 'Mathematics'), ('biography', 'Biography'), ('textbooks', 'Textbooks'), ('religion', 'Religion'), ('philosophy', 'Philosophy'), ('fiction', 'Fiction'), ('language', 'Languages & Literature'), ('history', 'History'), ('economics', 'Economics'), ('cs', 'Computer Science'), ('business', 'Business'), ('ba_economics', 'Business Administration & Economics'), ('magazines', 'Magazines & Journals'), ('management', 'Management'), ('children', "Children's Books"), ('arts', 'Arts & Humanities')], default='cs', max_length=50),
        ),
        migrations.AlterField(
            model_name='principalmessage',
            name='image',
            field=models.ImageField(default='principal_images/default.jpg', upload_to='principal_images/'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
