# Generated by Django 5.2 on 2025-05-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0025_delete_about_remove_book_author_remove_book_library_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='category',
            field=models.CharField(choices=[('language', 'Languages & Literature'), ('business', 'Business'), ('biography', 'Biography'), ('magazines', 'Magazines & Journals'), ('science', 'Science'), ('textbooks', 'Textbooks'), ('philosophy', 'Philosophy'), ('children', "Children's Books"), ('cs', 'Computer Science'), ('reference', 'Reference'), ('economics', 'Economics'), ('mathematics', 'Mathematics'), ('ba_economics', 'Business Administration & Economics'), ('arts', 'Arts & Humanities'), ('religion', 'Religion'), ('management', 'Management'), ('engineering', 'Engineering'), ('fiction', 'Fiction'), ('history', 'History')], default='cs', max_length=50),
        ),
    ]
