# Generated by Django 5.2 on 2025-05-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0026_news_slug_alter_librarybook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybook',
            name='category',
            field=models.CharField(choices=[('language', 'Languages & Literature'), ('business', 'Business'), ('cs', 'Computer Science'), ('arts', 'Arts & Humanities'), ('children', "Children's Books"), ('biography', 'Biography'), ('magazines', 'Magazines & Journals'), ('philosophy', 'Philosophy'), ('engineering', 'Engineering'), ('fiction', 'Fiction'), ('religion', 'Religion'), ('economics', 'Economics'), ('history', 'History'), ('reference', 'Reference'), ('textbooks', 'Textbooks'), ('management', 'Management'), ('ba_economics', 'Business Administration & Economics'), ('mathematics', 'Mathematics'), ('science', 'Science')], default='cs', max_length=50),
        ),
    ]
