# Generated by Django 5.2 on 2025-05-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0027_alter_librarybook_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='faculty_member',
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.CharField(default='Faculty Member Name', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='num_of_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='num_of_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='category',
            field=models.CharField(choices=[('arts', 'Arts & Humanities'), ('engineering', 'Engineering'), ('ba_economics', 'Business Administration & Economics'), ('business', 'Business'), ('textbooks', 'Textbooks'), ('management', 'Management'), ('philosophy', 'Philosophy'), ('cs', 'Computer Science'), ('biography', 'Biography'), ('fiction', 'Fiction'), ('mathematics', 'Mathematics'), ('history', 'History'), ('children', "Children's Books"), ('magazines', 'Magazines & Journals'), ('reference', 'Reference'), ('religion', 'Religion'), ('economics', 'Economics'), ('science', 'Science'), ('language', 'Languages & Literature')], default='cs', max_length=50),
        ),
    ]
