# Generated by Django 5.2 on 2025-05-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0028_rename_dept_image_department_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybook',
            name='category',
            field=models.CharField(choices=[('children', "Children's Books"), ('language', 'Languages & Literature'), ('magazines', 'Magazines & Journals'), ('arts', 'Arts & Humanities'), ('engineering', 'Engineering'), ('fiction', 'Fiction'), ('reference', 'Reference'), ('mathematics', 'Mathematics'), ('management', 'Management'), ('science', 'Science'), ('textbooks', 'Textbooks'), ('ba_economics', 'Business Administration & Economics'), ('cs', 'Computer Science'), ('religion', 'Religion'), ('philosophy', 'Philosophy'), ('history', 'History'), ('business', 'Business'), ('biography', 'Biography'), ('economics', 'Economics')], default='cs', max_length=50),
        ),
    ]
