# Generated by Django 5.2 on 2025-05-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0029_alter_librarybook_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='degree_type',
            field=models.CharField(choices=[('BS', 'Bachelor of Science'), ('MS', 'Master of Science'), ('BBA', 'Bachelor of Business Administration'), ('MBA', 'Master of Business Administration'), ('Diploma', 'Diploma'), ('PhD', 'Doctor of Philosophy'), ('Other', 'Other')], default='BS', max_length=20),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='category',
            field=models.CharField(choices=[('language', 'Languages & Literature'), ('arts', 'Arts & Humanities'), ('engineering', 'Engineering'), ('reference', 'Reference'), ('mathematics', 'Mathematics'), ('religion', 'Religion'), ('economics', 'Economics'), ('children', "Children's Books"), ('fiction', 'Fiction'), ('cs', 'Computer Science'), ('magazines', 'Magazines & Journals'), ('textbooks', 'Textbooks'), ('history', 'History'), ('management', 'Management'), ('science', 'Science'), ('ba_economics', 'Business Administration & Economics'), ('business', 'Business'), ('biography', 'Biography'), ('philosophy', 'Philosophy')], default='cs', max_length=50),
        ),
    ]
