# Generated by Django 5.2 on 2025-05-03 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0030_department_degree_type_alter_librarybook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybook',
            name='category',
            field=models.CharField(choices=[('reference', 'Reference'), ('cs', 'Computer Science'), ('engineering', 'Engineering'), ('language', 'Languages & Literature'), ('fiction', 'Fiction'), ('biography', 'Biography'), ('arts', 'Arts & Humanities'), ('history', 'History'), ('business', 'Business'), ('economics', 'Economics'), ('children', "Children's Books"), ('textbooks', 'Textbooks'), ('management', 'Management'), ('mathematics', 'Mathematics'), ('religion', 'Religion'), ('ba_economics', 'Business Administration & Economics'), ('magazines', 'Magazines & Journals'), ('science', 'Science'), ('philosophy', 'Philosophy')], default='cs', max_length=50),
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('image', models.ImageField(default='faculty/default.jpg', upload_to='faculty/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='gcms_sitehub.department')),
            ],
        ),
    ]
