# Generated by Django 5.2 on 2025-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0031_alter_librarybook_category_facultymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(choices=[('programming', 'Programming Lab'), ('multimedia', 'Multimedia Lab'), ('networking ', 'networking Lab'), ('Reserach ', 'Reserach Lab')], default='programming', max_length=100),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='category',
            field=models.CharField(choices=[('religion', 'Religion'), ('reference', 'Reference'), ('language', 'Languages & Literature'), ('philosophy', 'Philosophy'), ('ba_economics', 'Business Administration & Economics'), ('management', 'Management'), ('arts', 'Arts & Humanities'), ('magazines', 'Magazines & Journals'), ('mathematics', 'Mathematics'), ('engineering', 'Engineering'), ('history', 'History'), ('economics', 'Economics'), ('fiction', 'Fiction'), ('textbooks', 'Textbooks'), ('children', "Children's Books"), ('business', 'Business'), ('biography', 'Biography'), ('science', 'Science'), ('cs', 'Computer Science')], default='cs', max_length=50),
        ),
    ]
