# Generated by Django 5.2 on 2025-05-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0032_alter_facility_name_alter_librarybook_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarybook',
            options={},
        ),
        migrations.AlterField(
            model_name='facility',
            name='feature_1',
            field=models.CharField(blank=True, default='30 workstations with i7 processors', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='feature_2',
            field=models.CharField(blank=True, default='Latest programming tools and IDEs', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='feature_3',
            field=models.CharField(blank=True, default='Interactive learning systems', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(choices=[('programming', 'Programming Lab'), ('multimedia', 'Multimedia Lab'), ('networking', 'Networking Lab'), ('research', 'Research Lab')], default='programming', max_length=50, verbose_name='Lab Type'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='category',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('management', 'Management'), ('engineering', 'Engineering'), ('business', 'Business'), ('economics', 'Economics'), ('mathematics', 'Mathematics'), ('fiction', 'Fiction'), ('textbooks', 'Textbooks'), ('history', 'History'), ('biography', 'Biography'), ('science', 'Science'), ('arts', 'Arts & Humanities'), ('language', 'Languages & Literature'), ('reference', 'Reference'), ('philosophy', 'Philosophy'), ('religion', 'Religion'), ('ba_economics', 'Business Administration & Economics'), ('children', "Children's Books"), ('magazines', 'Magazines & Journals')], default='cs', max_length=50),
        ),
        migrations.AlterModelTable(
            name='librarybook',
            table=None,
        ),
    ]
