# Generated by Django 5.2 on 2025-05-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0034_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='slider/')),
                ('button1_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button1_url', models.URLField(blank=True, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button2_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
