# Generated by Django 5.2 on 2025-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0035_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AlterModelOptions(
            name='facultymember',
            options={'ordering': ['name'], 'verbose_name': 'Faculty Member', 'verbose_name_plural': 'Faculty Members'},
        ),
        migrations.AddField(
            model_name='facultymember',
            name='designation',
            field=models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('HOD', 'Head of Department'), ('Instructor', 'Instructor')], max_length=50, null=True),
        ),
    ]
