# Generated by Django 5.2 on 2025-05-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0036_delete_slider_alter_facultymember_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='head_of_department',
            new_name='faculty',
        ),
        migrations.AddField(
            model_name='department',
            name='hod_image',
            field=models.ImageField(blank=True, null=True, upload_to='hods/'),
        ),
    ]
