# Generated by Django 5.2 on 2025-05-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0037_rename_head_of_department_department_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymember',
            name='designation',
            field=models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('Instructor', 'Instructor')], max_length=50, null=True),
        ),
    ]
