# Generated by Django 5.2 on 2025-05-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0038_alter_facultymember_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.CharField(default='HOD Name', max_length=100),
        ),
    ]
