# Generated by Django 5.2 on 2025-05-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0039_department_head_of_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
