# Generated by Django 5.2 on 2025-05-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcms_sitehub', '0040_event_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='video_url',
        ),
    ]
